### ISSUE TITLE
bug in filter_high_expressers_gnorm.pl?

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#32]
Hello, does this script assume that when the data is strand-specific it must be paired? I'm running it on a strand-specific single end dataset and am getting errors like:

"Use of uninitialized value $reverse in scalar chomp at /gpfs/fs121/h/manduchi/Normalization/norm_scri
pts/filter_high_expressers_gnorm.pl line 144, <IN> line 63260."

**Comment by e-manduchi** [comment]
P.S. I did run the pipeline with the -se option on.

**Comment by eunjijunekim** [comment]
Hi,
filter_high_expressers_gnorm.pl file handles single end strand-specific datasets, but the runall_normalization.pl script was missing the $se flag for this script. Thank you for catching the bug.

**Comment by eunjijunekim** [comment]
fixed in v0.7-beta
