### ISSUE TITLE
depth for intron and exon quantication

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#33]
Hello, I've issues the command with the option -depthExon 5 and -depthIntron 5
However the first call to quantification of exon and introns appears to continue using the default:

Q.SAMPLE.quantify_exons_introns_u.sh

has -depthE 20 -depthI 10 specified.

**Comment by eunjijunekim** [comment]
Hi,
Depth of exon and intron is only used when -outputsam flag is used, so if the depth options are set correctly in Q.SAMPLE.quantify_exons_introns_u.outputsam.sh and Q.SAMPLE.quantify_exons_introns_nu.outputsam.sh files, that means PORT used 5 for depth of exon/intron. 

I will fix it so it doesn't show the depth options when they're not used.

**Comment by e-manduchi** [comment]
Thanks for the clarification. Oddly though, I discovered this after I got the script to exit before completing. When I manually modified my copy of quantify_exons_introns to use 5 as default depth and I resumed the pipeline, it went through with no error. Maybe it was a coincidence.

**Comment by eunjijunekim** [comment]
fixed in v0.7-beta
