### ISSUE TITLE
bug in run_normalization.pl

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#34]

**Comment by e-manduchi** [comment]
Sorry, here is the description: on line 480
this file is called:
my $list_for_intronquant = "$LOC/list_for_intronquants.$study.txt";
but it doesn't seem to exist. It looks like it should instead be
my $list_for_intronquant = "$LOC/list_for_intronquant.txt";

**Comment by eunjijunekim** [comment]
Are you sure your "get_list_for_intronquants.pl" script ran successfully? That's the script that generates the list for intronquant file and it names it like this: "$LOC/list_for_intronquants.$study.txt".

**Comment by e-manduchi** [comment]
I have empty log *err file for get_list_for_intronquants.err and in my READS dir I have a non-empty file named list_for_intronquants.txt

**Comment by eunjijunekim** [comment]
get_list_for_intronquants.pl script names the file "$LOC/list_for_intronquants.$study.txt" when -novel flag is used and "$LOC/list_for_intronquants.txt" when -novel flag is not used. I am going to fix it in get_list_for_intronquants.pl script to output "$LOC/list_for_intronquants.$study.txt" regardless of flag usage.

**Comment by eunjijunekim** [comment]
fixed in v0.7-beta
