### ISSUE TITLE
extending sam2cov support

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#35]
I see that currently sam2cov only supports alignments made with RUM of STAR. Would it be possible to extend to alignments made with gsnap?

**Comment by khayer** [comment]
I just released a new version that supports GSNAP. (sam2cov tag v0.0.5-beta)

**Comment by e-manduchi** [comment]
Super thx!

**Comment by eunjijunekim** [comment]
Elisabetta, for now, you can set "STAR = TRUE" and it should work for GSNAP alignments. I will modify the config file for the next release.

**Comment by e-manduchi** [comment]
Got it, thx.
