### ISSUE TITLE
READ_LENGTH

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#36]
The template.cfg file now has a READ_LENGHT field. Does this mean that PORT won't work if different samples in the study have different read lengths?

**Comment by eunjijunekim** [comment]
I would suggest equalizing the read lengths before running PORT.

However, PORT will work even if different samples have different read lengths. READ_LENGTH is a parameter used in get_master_list_of_intergenic_regions.pl and having different read lengths won't have a huge impact on the results. If you choose to use samples with varying read lengths, you can use the max read length in the config file.
