### ISSUE TITLE
high expressers filtered out?

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#37]
I've run PORT with the option -cutoff_highexp 10
I have 2 genes listed in percent_high_expressers, for each of these genes there is a sample where the % expressers is >20%. However I see these two genes listed in the  master_list_of_genes_counts spreadsheets with values=0 in all samples. I wonder if this is because the reads for these genes were filtered out, but when computing the final spreadsheet these genes were accidentally left in (and having no reads they got all 0).
A similar problem occurs for high expressed exons and introns.

**Comment by eunjijunekim** [comment]
If you use -cutoff_highexp option, all reads mapping to the highly expressed features (genes/exons/introns) are filtered out. So it makes sense for those features to have 0 as their counts, doesn't it? And if you look at the SPREADSHEET directory there should be FINAL_master_list_of_genes_counts file (exons and introns as well) which is generated from master_list_of_genes_counts by removing all rows with sum of counts = 0. 

I'm not sure if I understood your question correctly, so let me know if this doesn't answer your question.

**Comment by e-manduchi** [comment]
It wasn't really a question, rather a comment. I understand that the reads were filtered out so, after this operation, if one wanted to look at the counts for those genes they wouldn't find anything, However, leaving the genes in the normalized master_list_counts is misleading, because the reason the counts are 0 is because the reads were filtered out since the gene was a high expresser in some of the samples, not because the gene is not expressed. The actual expression of those genes is not 0 (indeed is very high at some samples) and a user who doesn't have this clear might misinterpret the spreadsheet as saying that this gene is not expressed. My suggestion is that these genes/exons are removed all together from any count list in the SPREADSHEET directory, to avoid confusion for the user.

**Comment by eunjijunekim** [comment]
The "master_list_of_genes_counts" files are considered intermediate files (PORT deletes them in the cleanup step if a user chooses to delete intermediate files). I can have the script that generates the FINAL spreadsheets to delete the intermediate spreadsheets if you think other users will find this confusing.

**Comment by e-manduchi** [comment]
Hmm, not sure. Some users might be interested in finding out which genes have no evidence for expression in any of the samples. So, they might not want to filter stuff which is 0 everywhere. For those users of course it would be important not to have this stuff confused with stuff that was filtered out (like high-expressers or mitochondrial).

**Comment by eunjijunekim** [comment]
With -cutoff_highexp option, PORT will estimate (using percent high expresser and normalized read counts) and put the counts of the filtered highly expressed genes back into the FINAL MIN spreadsheet and output an extra spreadsheet : FINAL_master_list_of_genes_counts_MIN.STUDYNAME.highExp.txt (only for the GENE level normalization).
