### ISSUE TITLE
feature branch mitochondrial chr still present in spreadsheet

### ISSUE THREAD

**Issue by e-manduchi** [itmat/Normalization#38]
The normalized data spreadsheets contain entries corresponding to the mitocondrial chromosomes, even though those reads were filtered out, so all values are 0. I guess these entries should be removed from the final sheet.

**Comment by eunjijunekim** [comment]
Again, please check the FINAL spreadsheets and see if the mitochondrial chromosomes are there. The final spreadsheets shouldn't have the mitochondrial chromosomes in them since all mitochondrial chromosome rows should have sum of counts = 0.

**Comment by e-manduchi** [comment]
This is similar to the analogous issue for high expressers. The problem is that having 0 in any of the files in the Normalized spreadsheet for these mitochondrial genes might lead the users to misinterpretation. The reason the 0 is there is due to filtering and not necessarily to lack of expression and a user who is not familiar with how PORT works, might not have this clear and misinterpret those spreadsheet.
