### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by xflicsu** [itmat/Normalization#43]
Hello PORT developer,

```
 I got the SPREADSHEETS information of genes. 
```

id      N1     N2     N3     T1    T2     T3     geneCoordinate  geneSymbol
gene:ENSMUSG00000000001 22      16      22      29      30      26      chr3:107910198-107949064        Gnai3
gene:ENSMUSG00000000028 0       4       4       0       2       1       chr16:18780540-18812080 Cdc45
gene:ENSMUSG00000000037 3       0       2       0       0       2       chrX:157555125-157696145        Scml2
gene:ENSMUSG00000000049 56      56      58      70      57      66      chr11:108204668-108275710       Apoh
gene:ENSMUSG00000000056 259     278     266     110     104     94      chr11:121098567-121117170       Narf

We have two groups of samples.
I wonder the whether these values need to be re-normalize to TPM/RPKM.
And can I directly input these value to DESeq to identify differential expression?
Is it necessary to re-normalize by using DESeq?
BTW, is there any tool to convert this value to TPM or RPKM?

**Comment by greggrant** [comment]
Hi Xianfeng, thanks for your interest in PORT.  The answer to your question
is "no" once you get the spreadsheet out of PORT no further normalization
is necessary.  We definitely advise against using the TPM, RPKM or anthing
like that.  The counts are already fully normalized after PORT.
Best Regards, Greg

**Comment by xflicsu** [comment]
Thanks for you response! It is very useful for my sub-analysis.
